name: Tests on Node.js
on: [push, pull_request]

jobs:
  test:
    name: "Node.js v${{matrix.node}}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          # Better SQLite3 v6 depends on Node >= v8 and < 16.
          - "8"
          - "9"
          - "10"
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: {node-version: "${{matrix.node}}"}
      - run: npm install
      - run: make spec
